// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Produccion_Back.Datos.Modelos;

public partial class Servicio
{
    public int IdServicio { get; set; }

    public string Nombre { get; set; }

    public decimal Costo { get; set; }

    public virtual ICollection<DetalleTurno> DetalleTurnos { get; set; } = new List<DetalleTurno>();
}