// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Produccion_Back.Datos.Modelos;

public partial class Turno
{
    public int IdTurno { get; set; }

    public DateTime Fecha { get; set; }

    public int IdCliente { get; set; }

    public virtual ICollection<DetalleTurno> DetalleTurnos { get; set; } = new List<DetalleTurno>();
}